WRITING_TOPICS = [
 
    # ── Beginner ──────────────────────────────────────────
    {"topic": "Describe your ideal weekend", "level": "Beginner", "hint": "Use present tense and descriptive adjectives."},
    {"topic": "Describe your favorite food and how to make it", "level": "Beginner", "hint": "Use imperative sentences for instructions."},
    {"topic": "Describe your morning routine", "level": "Beginner", "hint": "Use frequency adverbs: always, usually, sometimes."},
    {"topic": "Describe your dream job", "level": "Beginner", "hint": "Use 'I want to' and 'because' to give reasons."},
    {"topic": "Write about your favorite season and why you like it", "level": "Beginner", "hint": "Use adjectives to describe the weather and activities."},
    {"topic": "Describe your bedroom or home", "level": "Beginner", "hint": "Use 'there is/there are' and location words like next to, behind, in front of."},
    {"topic": "Write about your favorite animal", "level": "Beginner", "hint": "Describe its appearance, habitat, and why you like it."},
    {"topic": "What do you usually do after school or work?", "level": "Beginner", "hint": "Use simple present tense and time expressions like first, then, after that."},
    {"topic": "Describe your best friend", "level": "Beginner", "hint": "Use adjectives for personality and appearance."},
    {"topic": "What is your favorite movie or TV show? Why?", "level": "Beginner", "hint": "Use 'because' and simple opinions like 'I think', 'I feel'."},
    {"topic": "Write about a sport or hobby you enjoy", "level": "Beginner", "hint": "Explain what it is, how to do it, and why you like it."},
    {"topic": "Describe your family", "level": "Beginner", "hint": "Use family vocabulary and simple descriptive sentences."},
    {"topic": "What is your favorite holiday? Why?", "level": "Beginner", "hint": "Use present and past tense to describe traditions and memories."},
    {"topic": "Write about a place you want to visit someday", "level": "Beginner", "hint": "Use 'I want to' and 'because' with descriptive details."},
    {"topic": "Describe a typical day in your life", "level": "Beginner", "hint": "Use time expressions: in the morning, at noon, in the evening."},
    {"topic": "What is your favorite subject in school and why?", "level": "Beginner", "hint": "Give at least two reasons using 'because' and 'also'."},
    {"topic": "Write about something you are good at", "level": "Beginner", "hint": "Use 'I am good at ~ing' and explain how you learned it."},
    {"topic": "Describe your favorite restaurant or cafe", "level": "Beginner", "hint": "Use sensory words: taste, smell, look, feel."},
    {"topic": "What do you do to relax after a busy day?", "level": "Beginner", "hint": "Use present tense and sequence words."},
    {"topic": "Write about your favorite childhood toy or game", "level": "Beginner", "hint": "Use past tense: played, loved, used to."},
 
    # ── Intermediate ──────────────────────────────────────
    {"topic": "Write about a memorable trip you took", "level": "Intermediate", "hint": "Use past tense and sequence words like first, then, finally."},
    {"topic": "Write about a person who has influenced your life", "level": "Intermediate", "hint": "Include specific examples and emotions."},
    {"topic": "Write about a challenge you overcame", "level": "Intermediate", "hint": "Use past tense and emotion words."},
    {"topic": "Write about an important invention in history", "level": "Intermediate", "hint": "Explain cause and effect using 'as a result' and 'therefore'."},
    {"topic": "Describe a time when you felt proud of yourself", "level": "Intermediate", "hint": "Use past tense and include what happened, how you felt, and what you learned."},
    {"topic": "Write about the advantages and disadvantages of social media", "level": "Intermediate", "hint": "Use contrast words: however, on the other hand, although."},
    {"topic": "Describe a cultural tradition from your country", "level": "Intermediate", "hint": "Explain what it is, when it happens, and why it is important."},
    {"topic": "Write about a book that changed your perspective", "level": "Intermediate", "hint": "Summarize the story briefly, then explain its impact on you."},
    {"topic": "What would you do if you won the lottery?", "level": "Intermediate", "hint": "Use conditional sentences: If I won..., I would..."},
    {"topic": "Describe your experience learning English", "level": "Intermediate", "hint": "Include challenges, progress, and goals using past and present tense."},
    {"topic": "Write about a mistake you made and what you learned from it", "level": "Intermediate", "hint": "Use past tense and reflection phrases: I realized, I learned that."},
    {"topic": "Compare living in a city vs. living in the countryside", "level": "Intermediate", "hint": "Use comparison words: while, whereas, in contrast, similarly."},
    {"topic": "Write about your goals for the next five years", "level": "Intermediate", "hint": "Use future tense: will, am going to, plan to, hope to."},
    {"topic": "Describe a festival or event you have attended", "level": "Intermediate", "hint": "Use past tense and vivid sensory details."},
    {"topic": "Write about how technology has changed daily life", "level": "Intermediate", "hint": "Compare past and present using 'used to' and 'now'."},
    {"topic": "Describe a time when you helped someone", "level": "Intermediate", "hint": "Include the situation, what you did, and how it made you feel."},
    {"topic": "Write about the importance of learning a foreign language", "level": "Intermediate", "hint": "Give at least three reasons using linking words: first, furthermore, finally."},
    {"topic": "Describe your dream house", "level": "Intermediate", "hint": "Use conditional and descriptive language: It would have..., I would want..."},
    {"topic": "Write about a news story that surprised you recently", "level": "Intermediate", "hint": "Summarize the story and express your reaction and opinion."},
    {"topic": "Compare two movies or TV shows you have watched", "level": "Intermediate", "hint": "Use comparison structures: both, neither, while, however."},
 
    # ── Advanced ──────────────────────────────────────────
    {"topic": "Should social media be regulated by the government? Share your opinion.", "level": "Advanced", "hint": "Use argument structures: claim, evidence, counterargument."},
    {"topic": "Is remote work better than working in an office?", "level": "Advanced", "hint": "Compare pros and cons using contrast words like however, on the other hand."},
    {"topic": "How will AI change education in the next 10 years?", "level": "Advanced", "hint": "Use future tense and conditional sentences."},
    {"topic": "Should animals be kept in zoos? Argue your position.", "level": "Advanced", "hint": "Use formal vocabulary and logical connectors."},
    {"topic": "Is social media doing more harm than good to society?", "level": "Advanced", "hint": "Present both sides and give a clear concluding opinion."},
    {"topic": "Should university education be free for everyone?", "level": "Advanced", "hint": "Use argument and counterargument structure with evidence."},
    {"topic": "Discuss the ethical issues surrounding artificial intelligence", "level": "Advanced", "hint": "Use academic vocabulary: ethical, implication, autonomous, accountability."},
    {"topic": "Is globalization beneficial or harmful to developing countries?", "level": "Advanced", "hint": "Use cause and effect language: leads to, results in, consequently."},
    {"topic": "Should the voting age be lowered to 16?", "level": "Advanced", "hint": "Make a clear claim, support with reasoning, and address counterarguments."},
    {"topic": "How should governments address climate change?", "level": "Advanced", "hint": "Use modal verbs for suggestions: should, must, ought to, need to."},
    {"topic": "Is it ethical to use animals for medical research?", "level": "Advanced", "hint": "Acknowledge both perspectives before stating your position."},
    {"topic": "Discuss the impact of smartphones on human relationships", "level": "Advanced", "hint": "Use hedging language: it could be argued, some may suggest, research indicates."},
    {"topic": "Should capital punishment be abolished worldwide?", "level": "Advanced", "hint": "Use formal discourse markers: furthermore, nevertheless, in contrast."},
    {"topic": "To what extent does social class determine life outcomes?", "level": "Advanced", "hint": "Use nuanced language and avoid absolute claims: tends to, may influence, can contribute to."},
    {"topic": "Is it possible to achieve true gender equality in the workplace?", "level": "Advanced", "hint": "Use data or examples to support claims, and address structural barriers."},
    {"topic": "Discuss the pros and cons of a four-day work week", "level": "Advanced", "hint": "Structure your essay with a clear introduction, body paragraphs, and conclusion."},
    {"topic": "How does the media influence public opinion?", "level": "Advanced", "hint": "Use passive voice and impersonal structures to sound more academic."},
    {"topic": "Should wealthy nations accept more refugees?", "level": "Advanced", "hint": "Incorporate ethical, economic, and humanitarian perspectives."},
    {"topic": "Is online education as effective as traditional classroom learning?", "level": "Advanced", "hint": "Compare both methods using evidence and personal insight."},
    {"topic": "Discuss whether economic growth and environmental sustainability can coexist", "level": "Advanced", "hint": "Use complex sentence structures and academic connectors."},
]